### ISSUE TITLE
Unclear permission for modpacks.

### ISSUE THREAD

**Issue by Divineaspect** [delvr/Repose#1]
Hey, I'm looking to use your mod for a modpack, Storybook, and I noticed that while Streams has  the line "May I include this mod in my modpack? You may include this mod and API in a modpack if you provide author credit and a link to this forum thread." Repose is lacking a similar line.
 My apologies if this is intentional.

**Comment by delvr** [comment]
Hi Divineaspect,
this was not intentional; Repose should be available under the same permissions as Streams. I just updated the forum post to reflect this.
