### ISSUE TITLE
Suggestion-Ability to Edit the Block List for Granular/Natural Stone Blocks

### ISSUE THREAD

**Issue by WenXin20** [delvr/Repose#10]
It would be nice if I could edit the block lists by manually adding blocks to the list in the config.
I am using 1.10.2

By the way, the issue page in curseforge for this mod took me to the Streams github instead.

**Comment by WenXin20** [comment]
Nevermind, I just didn't look at the config close enough.

**Comment by delvr** [comment]
Thanks for the update. Note that someone reported a bug with the config file resetting itself, which I'm investigating. Also, I fixed the curseforge issues link, thanks for letting me know.

**Comment by WenXin20** [comment]
I thought it was resetting itself too, but then I realized that it was just automatically sorting itself alphabetically after new blocks were added. Could be what someone else saw as well.
