### ISSUE TITLE
Crash from Repose

### ISSUE THREAD

**Issue by ChiefLogan3010** [delvr/Repose#17]
I seem to be experiencing a crash in the latest curse release for both repose and farseek.

https://gist.github.com/ChiefLogan3010/b0c8d7361ca0b956b754b43be31cda1e

**Comment by delvr** [comment]
Hi ChiefLogan3010, thanks for reporting this. I haven't been able to reproduce this behavior, but the new Farseek 2.2.4 release includes a patch that should guard against this behavior for certain modded blocks that misbehave in the Ore Dictionary. Please give it a try and re-open this issue if this still happens for you. Thanks!
