### ISSUE TITLE
Feature Reqest: Configurable Granular Materials

### ISSUE THREAD

**Issue by Divineaspect** [delvr/Repose#2]
I'd like to request the ability to configure which materials are considered granular.

The problems I'm trying to solve include:
the disintegration of slime islands (TinCon) pouring rivers of slime.
Rampant Twilight forest cave ins destroying the portal back.
Valid nether portal locations on sheets of soulsand falling away into infinite fields of lava.

 I'm equally open to some other solution to these problems, that's just the one that occurs to me.

I don't suppose falling/spreading/flowing liquid source blocks might also be in the future.

**Comment by Gio** [comment]
@Divineaspect Open ./config/repose.properties and set "repose.soilFall", "repose.blockSpread", and "repose.avalanches" to false; that should solve some odd interactions.

**Comment by Divineaspect** [comment]
I understand how it works by default. I enjoy the falling and avalanches. Hense making a new feature request instead of using existing configs.

**Comment by Gio** [comment]
@Divineaspect I mentioned it as a workaround for anyone experiencing the same issue. The "@" was by habit, honestly. Since I'm not a dev, I can't reply to the feature request aspect.

**Comment by O13SC3N3** [comment]
Im sure this would fall under this as well. Maybe some config options to add blocks for repose to interact with? Cuz I noticed with blocks generated over stone by UBC repose will NOT scale up the normal 1 block up 1 block. Grans and Dirt still works fine. Maybe UBC support? I haven't checked to see if climate control, or rtg effects this in someway.

**Comment by delvr** [comment]
This feature is now implemented in version 1.9.4-1.4. Please read the "Configuration" section in the [forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076319-repose-walkable-soil-slopes-give-your-spacebar-a) for details, and let me know of any questions or issues. Thanks!
