### ISSUE TITLE
Crash when breaking blocks

### ISSUE THREAD

**Issue by cadaverous-eris** [delvr/Repose#21]
Using the latest version of the mod and Farseek API. Crash happens rarely when breaking blocks. I thought disabling the extra block physics would prevent this crash, but apparently I was wrong.

Crashlog: https://pastebin.com/dkaiLu7g

**Comment by delvr** [comment]
Hi the-releast-stu, your version of Farseek isn't actually the latest - updating to 2.2.5 will fix this issue. Cheers!

**Comment by cadaverous-eris** [comment]
Ah, whoops. Not sure how I missed that.

**Comment by delvr** [comment]
No worries :)
