### ISSUE TITLE
Falling blocks not settle on transparent blocks, sometimes duplicate!

### ISSUE THREAD

**Issue by Tokeli** [delvr/Repose#24]
Minecraft 1.12.2
Repose 1.12-1.6
Farseek 1.12-2.3

If a falling block drops onto a transparent block (tested with ice, glass panes, glass) it does not settle and continuously makes the falling-block noise, and will only settle if the transparent block beneath is removed.

Additionally, if sand or gravel are quickly dropped onto transparent blocks, they seem to duplicate when falling off onto non-transparent blocks.  If spammed hard enough, you'll have a pile of sand that rapidly flickers and cannot be removed without explosives, and that will just spawn new sand if you mine out a block beneath.

Tested with nothing but Repose, Farseek, and JEI.

**Comment by delvr** [comment]
Thanks Tokeli for reporting this, I'll look into it and get back to you.

**Comment by delvr** [comment]
This is fixed in 1.6.1, please let me know of any issues.
