### ISSUE TITLE
Possible incompatibility with Cases and Primitive Mobs

### ISSUE THREAD

**Issue by abracadabramods** [delvr/Repose#35]
Going through my too-many mods to find a playable configuration, looks like there's some kind of conflict between Cases 0.3.2 beta, Repose 1.12-1.6.1, and Primitive Mobs 1.1.6 beta.

[pastebin link](https://pastebin.com/FxkHBmLC)

I'm not too worried about it, I'll just have to remember split them up over different profiles, but it might be something you want to look at for compatibility/bugs you didn't notice before. Or maybe it's an endemic incompatibility. Good luck and thanks for the mod either way!

(cross-posting to all three mods just in case)

**Comment by delvr** [comment]
Hi @abracadabramods, looking at the stack trace the error seems to come from Cases. Here's a similar crash report I found online where Cases is involved but not Repose: https://pastebin.com/mqNWEp73

Not sure if you've opened an issue with Cases, but this seems to be their tracker: https://minecraft.curseforge.com/projects/cases/issues
