### ISSUE TITLE
Feature Reqest：Add configuration to disable walking

### ISSUE THREAD

**Issue by luoxingzlx** [delvr/Repose#36]
Can you add a configuration to make the block only affected by gravity without becoming a staircase? I just want to achieve the same effect as TerraFirmaCraft and don't want the player to cross the block directly, and there are some things in my modpack that are duplicated with this function, like Free Runners by Mekanism

**Comment by delvr** [comment]
Hi luoxingzlx, to disable the sloping behavior just go to the mod configuration screen ("Mods" in the main game menu, then select Repose and click "Config") and change "Sloping Blocks" to "None".

(If running with a server, make sure you change both the client configurations and the server's `config/repose.properties` file.)

If this doesn't work for you please let me know.

Happy new year!

**Comment by luoxingzlx** [comment]
Thank you very much for your reply, Happy New Year!
