### ISSUE TITLE
[Bug] Small animals suffocate when on edge of sloping blocks

### ISSUE THREAD

**Issue by SpeakerHornet** [delvr/Repose#41]
Title.
I tested this with latest Repose and Farseek. Small animals such as bunnies walk and jump onto sloping block (it was sand in my case) and they get suffocated and die. Also happens with goats from Better Animals+.

**Comment by delvr** [comment]
Just released 1.6.3 to fix this, please let me know if it happens again.

(Note that _large_ animals suffocating into walls is a [separate vanilla bug](https://bugs.mojang.com/browse/MC-13632).)

**Comment by ilvrak** [comment]
I checked:

hamster,chicken - norm
rabbit - still suffocate

**Comment by delvr** [comment]
Hi @ilvrak , I tested the latest Repose and rabbits seem to be doing fine. Do you have any other mods that might change their behavior somehow? Could you post a picture or video? Thanks!

**Comment by netmc** [comment]
This also happens with bunnies and such from Animalia.  They take damage when they jump and land on the slope. (Just tested today.)

**Comment by ilvrak** [comment]
yes, i mean, Rabbits from Animania! )
![2019-05-29_08 43 08](https://user-images.githubusercontent.com/16130834/58521160-14a3f600-81ee-11e9-8d23-d9077719fcea.png)

**Comment by delvr** [comment]
Ah, that makes sense, thanks. I'll work on fixing that.

**Comment by delvr** [comment]
Should be fixed in Repose 1.6.4.
