### ISSUE TITLE
[Bug] Incopatibility with Chop Down Updated

### ISSUE THREAD

**Issue by SpeakerHornet** [delvr/Repose#42]
Chop Down Updated mod makes trees fall when the bottom of a tree is broken. Incompatible part is that leaves blocks fall into each other and form into just one row of one leaves as opposed to multi layered bush. Here are some pictures explaining the above:
![2019-05-23_19 21 53](https://user-images.githubusercontent.com/26009450/58273315-b8297c80-7d90-11e9-8de1-e0fe6e436a13.png)

Expected:
![2019-05-23_19 23 58](https://user-images.githubusercontent.com/26009450/58273346-d2635a80-7d90-11e9-8c97-6343a3ea89c5.png)

Actual behavior:
![2019-05-23_19 22 03](https://user-images.githubusercontent.com/26009450/58273569-430a7700-7d91-11e9-8978-1dd27367ad2a.png)

Chop Down Updated version: 1.2.4
Repose: 1.6.3
Farseek: 2.3.2
Forge: 14.23.5.2795

**Comment by delvr** [comment]
Should be fixed in Repose 1.6.4.
