### ISSUE TITLE
Wither Construction

### ISSUE THREAD

**Issue by Divineaspect** [delvr/Repose#6]
how does one?

**Comment by delvr** [comment]
Sorry, could you clarify your question? It doesn't seem related to the Repose mod.

**Comment by Divineaspect** [comment]
The wither is constructed by placing 4 soul sand (a material which slopes, etc, in repose) in a T shape, with three wither skulls atop it. The first  step is not achievable due to repose causing soul sand to flow.

Do you have a method to bypass this issue?

**Comment by delvr** [comment]
Ah, I see what you mean now. :-) Probably the simplest way would be to open Mod Options in the pause screen, find Repose in the list, click Config and disable the Soil Fall option. You can then reactivate it once your Wither is done. Let me know if this works for you.

**Comment by Divineaspect** [comment]
Ineffective on a server, or when shipping with a mod pack. Which is where I'm doing the testing and what I'm using it for.

**Comment by Divineaspect** [comment]
apparently you can construct the wither sideways, which also works.
